Foreword 前言
the-road-to-learn-react/the-road-to-learn-react-chinese pull request #14
Opened 2017-12-03 07:41 UTC by LeiZeng

译文翻译完成一半 #

2017-12-03 12:03 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +通过《》，我想在您陷入到庞大的React生态圈之前，奠定一个良好的基础。她会通过一个真实可用的React应用来解释基本概念，设计模式以及一些最佳实践。
「陷入」翻译得很恰当啊，😂
貌似“奠定一个良好的基础”前端主语不对，“broad”的比较级应该要翻出来。maybe 可以是“在开始深入到更广泛的 React 生态系统之前提供一个基础。”

2017-12-03 12:07 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +《》会教您一些React的基础知识。通过这套教程，您可以用纯React构建一个真正可用的应用程序，而不需要去理会其他复杂的工具。从开发环境的准备到部署上线的所有过程都会被一一介绍。本书每一章都包含一些额外的索引资料以及课后练习。在读完本书之后，您会有能力依靠自己构建一个React应用。这些资料会被我，Robin Wieruch，以及整个社区维护和更新。
1. 我们应该跟其他人统一一下，到底是用“您” or “你”。
2. 被动->主动句式：我将为您逐一介绍从准备开发环境到部署上线的全过程

2017-12-03 12:11 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +您会学着构建您自己的React应用。她会涵盖一些真正可用的功能，比如分页，客户端缓存，以及像搜索和排序这样的交互功能。另外在这个过程中，您会慢慢从JavaScript ES5过渡到JavaScript ES6.我希望这本书能点燃你对React和JavaScript的热情，并让你能够开始使用他们。
哈哈哈，为啥会是“她”呢，😂 原来你一直把 React 当妹纸。。。

就翻译成“这个应用将会涉及……” 会不会更顺一点

2017-12-04 01:52 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +《》会教您一些React的基础知识。通过这套教程，您可以用纯React构建一个真正可用的应用程序，而不需要去理会其他复杂的工具。从开发环境的准备到部署上线的所有过程都会被一一介绍。本书每一章都包含一些额外的索引资料以及课后练习。在读完本书之后，您会有能力依靠自己构建一个React应用。这些资料会被我，Robin Wieruch，以及整个社区维护和更新。
嗯，有道理，被动语态中文很别扭

2017-12-04 01:52 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +通过《》，我想在您陷入到庞大的React生态圈之前，奠定一个良好的基础。她会通过一个真实可用的React应用来解释基本概念，设计模式以及一些最佳实践。
很细致！

2017-12-04 01:52 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +您会学着构建您自己的React应用。她会涵盖一些真正可用的功能，比如分页，客户端缓存，以及像搜索和排序这样的交互功能。另外在这个过程中，您会慢慢从JavaScript ES5过渡到JavaScript ES6.我希望这本书能点燃你对React和JavaScript的热情，并让你能够开始使用他们。
这里其实有很多代词，我几乎都是用的她，这本书，React，这个应用的指代，还是个选择吧，他她它

2017-12-04 02:04 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +您会学着构建您自己的React应用。她会涵盖一些真正可用的功能，比如分页，客户端缓存，以及像搜索和排序这样的交互功能。另外在这个过程中，您会慢慢从JavaScript ES5过渡到JavaScript ES6.我希望这本书能点燃你对React和JavaScript的热情，并让你能够开始使用他们。
忠于原著的话，it还是应该用它的，哎~

2017-12-06 13:40 UTC, JimmyLv commented on README-cn.md
> +[The Road to learn React](https://www.robinwieruch.de/the-road-to-learn-react/)官方代码仓库。另外，你还可以在这里找到 [源代码](https://github.com/the-road-to-learn-react/hackernews-client)和[完整课程](https://roadtoreact.com/)
「这是 xxx  官方代码仓库」？不然显得有点儿奇怪。

[ 源代码 ] 和 [ 完整课程 ] 中文之间就不用有空格啦。

2017-12-06 15:13 UTC, JimmyLv requested changes

2017-12-06 15:13 UTC, JimmyLv commented on README-cn.md
> +您可以通过提交新的问题(Issue)和代码改动(Pull Requests)来帮助改进这本书。
Issues 和 PR  不用翻译了吧，而且 Issues 翻译成问题好像也有点儿严重，😂

2017-12-06 15:13 UTC, JimmyLv commented on README-cn.md
> +您可以提交代码改动（Pull Request)来纠正拼写或者用更具体的方式来介绍某个课程。在写这样一本技术类的书籍时，会很容易进入盲区，不会发现一些内容需要更多解释和过多解释。
或者用更具体的方式来介绍某个课程。-->  ，或是为某个课程补充更多细节。

加个`，`号断句吧，中文句子一般会短一些。explains 不一定翻译成「补充」，应该有更好的词。

2017-12-06 15:13 UTC, JimmyLv commented on README-cn.md
> +您可以提交代码改动（Pull Request)来纠正拼写或者用更具体的方式来介绍某个课程。在写这样一本技术类的书籍时，会很容易进入盲区，不会发现一些内容需要更多解释和过多解释。
-> 你会对有待解释的东西和已经解释清楚的东西视而不见。

2017-12-06 15:13 UTC, JimmyLv commented on README-cn.md
> +另外，在遇到问题时，您可以在Github创建新的问题(Issue)。为了让这些问题尽快和更容易解决，请提供更多细节，比如报错信息，截图，哪一页出现的问题，您的node版本(命令: node -v)以及你的代码仓库地址。这些细节不全是必需的，但大部分可以为修复问题和改进本书提供很大的帮助。
报错信息、截图、出错页码、当前 node 版本

`，` --> `、`
命令 --> 命令行

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +通过《》，在开始陷入到更庞大的React生态圈之前，我想为您奠定一个良好的基础。它会通过一个真实可用的React应用来解释基本概念，设计模式以及一些最佳实践。
基本概念、设计模式以及最佳实践。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +您会学着构建您自己的React应用。这个应用会涉及一些真正可用的功能，比如分页，客户端缓存，以及像搜索和排序这样的交互功能。另外在这个过程中，您会慢慢从JavaScript ES5过渡到JavaScript ES6.我希望这本书能承载着我对React和JavaScript的热情，并让您能够开始您的开发旅程。
「学着」有点儿奇怪，这里没有正在进行式，可能「你将会学到xxx」会好点儿。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +您会学着构建您自己的React应用。这个应用会涉及一些真正可用的功能，比如分页，客户端缓存，以及像搜索和排序这样的交互功能。另外在这个过程中，您会慢慢从JavaScript ES5过渡到JavaScript ES6.我希望这本书能承载着我对React和JavaScript的热情，并让您能够开始您的开发旅程。
1. captures 有「充分体现」的意思，即「希望这本能够充分体现我…」（看着「承载」有点儿奇怪我就去翻了字典
2. 并让您能够开始您的开发旅程。--> 并帮助你开启你的旅程

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +> **[Muhammad Kashif](https://twitter.com/appsdevpk/status/848625244956901376):** "The Road to Learn React is a unique book that I recommend to any student or professional interested in learning reac
这里的professional就是「专业人士」的意思，可做名词。

是一本独一无二的书，我推荐给任何想要学习 React 基础（或提升 React 水平？）的学生或专业人士。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Muhammad Kashif](https://twitter.com/appsdevpk/status/848625244956901376):** “《》是一本独一无二的书，我推荐给所有的学生或者对React有专业兴趣的初级或高级的读者。她是一个包括了很难在其他地方找到的有启发性的小提示和技术点的合集，最棒的是书中的例子和引用都很缜密的放到一起解决了同一个问题，我有17年的互联网和桌
是一个包括了 xxx 的合集 --> 富含
很难在其他地方找到的 --> 绝无仅有

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Muhammad Kashif](https://twitter.com/appsdevpk/status/848625244956901376):** “《》是一本独一无二的书，我推荐给所有的学生或者对React有专业兴趣的初级或高级的读者。她是一个包括了很难在其他地方找到的有启发性的小提示和技术点的合集，最棒的是书中的例子和引用都很缜密的放到一起解决了同一个问题，我有17年的互联网和桌
references to 提及/涉及，大致就是「书中使用了很多示例，涉及了很多实际问题」
before reading this book 没翻译出来，「在阅读本书之前」。
—> 「这本书就像魔术一样有用」。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Nicholas Hunt-Walker, Instructor of Python at a Seattle Coding School](https://twitter.com/nhuntwalker/status/845730837823840256):** “这是一本我用过的最严谨和最实用的编程书籍。一本完整的React和ES6使用说明。”
用过？书籍还是读过的吧，或者 worked through 有更好的翻译，不如就读过吧。

而且还有 one of，最实用的编程书籍之一

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Austin Green](https://twitter.com/AustinGreen/status/845321540627521536):** “非常感谢，真的很喜欢这本书。完美的学习曲线，不管是React，ES6，还是抽象编程概念。”
higher level 更高层次的？

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Nicole Ferguson](https://twitter.com/nicoleffe/status/833488391148822528):** “这个周末我跟着Robin的课程，学习React。发现这一切太有意思了，竟然让我几乎感到了愧疚。”
「跟着」很妙！
不用，吧「这个周末我跟着 Robin 的课程学习 React。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Nicole Ferguson](https://twitter.com/nicoleffe/status/833488391148822528):** “这个周末我跟着Robin的课程，学习React。发现这一切太有意思了，竟然让我几乎感到了愧疚。”
这几乎让我感到羞愧。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Eric Priou](https://twitter.com/erixtekila/status/840875459730657283):** “Robin的《》是必读的一本书。简明扼要的介绍了React和Javascript。”
简明扼要「地」介绍

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**一个新手开发:** “作为一个新手开发，我刚刚完成了这本书的学习，非常感谢写了这本书。她非常容易上手，我相信自己在接下来的几天可以开始从头开发一个新应用。这本书比官方的React入门文档好很多，我之前有试过（但是我完全无法继续下去，因为缺乏一些细节的知识点）。每个章节后面的练习题对我有很好的激励效果。”
开发新手 or 新手开发者，总之应当是个名词。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**一个新手开发:** “作为一个新手开发，我刚刚完成了这本书的学习，非常感谢写了这本书。她非常容易上手，我相信自己在接下来的几天可以开始从头开发一个新应用。这本书比官方的React入门文档好很多，我之前有试过（但是我完全无法继续下去，因为缺乏一些细节的知识点）。每个章节后面的练习题对我有很好的激励效果。”
lack of detail 应当指的是 React 教程，tutorial 并不能作为入门文档。couldn't 指的是之前（过去式）没有完成而已。

这本书比我之前试过的 React 官方教程好很多，（由于缺乏细节我并未能够完成）

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**一个学生:** “这是最好的学习React的一本书。我们可以一边做练习项目，一边学习知识点，然后还能紧扣我们的学习主题。我发现‘边码边学’是最好的掌握编程的方法，而这本书完完全全是这样教我的。”
用正体引号吧，「边码边学」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Thomas Lockney](https://www.goodreads.com/review/show/1880673388):** “这是一本非常扎实的介绍React的书，不会试着把其他的工具混在一起。我本来只想尝试理解看看这本书到底讲了什么，然后我得出了上面的结论。我并没有跟着所有的脚注来学习我还没有注意到的新的ES6语法（我当然不会说我一直没有注意到，Bob）（译者注，这个是在博
「不会试着把其他的工具混在一起。」其实没有任何工具的字眼啦。

「而不是试着把事情搞复杂。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Thomas Lockney](https://www.goodreads.com/review/show/1880673388):** “这是一本非常扎实的介绍React的书，不会试着把其他的工具混在一起。我本来只想尝试理解看看这本书到底讲了什么，然后我得出了上面的结论。我并没有跟着所有的脚注来学习我还没有注意到的新的ES6语法（我当然不会说我一直没有注意到，Bob）（译者注，这个是在博
“但是我想很肯定的对那些没有及时了解到这些新功能并且很勤奋的跟着练习的朋友们说，你们可以额外学到很多书中没有的知识。”
这句太长了，试着断句一下呢？

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**[Thomas Lockney](https://www.goodreads.com/review/show/1880673388):** “这是一本非常扎实的介绍React的书，不会试着把其他的工具混在一起。我本来只想尝试理解看看这本书到底讲了什么，然后我得出了上面的结论。我并没有跟着所有的脚注来学习我还没有注意到的新的ES6语法（我当然不会说我一直没有注意到，Bob）（译者注，这个是在博
额外学到？努力勤奋的话，那当然接下来的句子就是「你能学到的不仅仅是这本书所教的东西。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +这本书可以给予任何人学习React的条件。但是，由于这本书一开始是用英文写的，并不是所有人都有能力使用这些资源。所以我想用这个项目来支持那些可以让儿童在开发过程中学习英文的其他项目。
「这本书应该能让任何人都可以学习 React。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +这本书可以给予任何人学习React的条件。但是，由于这本书一开始是用英文写的，并不是所有人都有能力使用这些资源。所以我想用这个项目来支持那些可以让儿童在开发过程中学习英文的其他项目。
这里的 developing 完全木有开发的意思啦，应该是发展中国家，😂

「因此，我想用这个项目来支持那些在发展中国家教孩子们英语的项目。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**这本书用的是最新版本的React吗？** 本书总是会在React更新时发布一个新的版本。通常React更新后本书很快就会有新的更新。因为这本书是自我更新的，所以我可以随时更新。
这里表达的重点就是「自出版」，这是电子书可以随时更新，而「传统出版」的书会很快过时。

「这本书总是会随着 React 版本而更新。通常情况下书籍在发行后很快就过时了。」

「因为这本书是自出版的，所以我可以随时更新它。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**这本书包括Redux的内容吗？** 不包括。不过我写了第二本书。《》会给你奠定一个坚实的基础，这样你可以继续之后的高阶内容。同样一个应用，在这本书里面会展示给你一个代码实现，可以不用Redux来搭建React应用。在读完这本书之后，你应该有能力自己搭建一个不用Redux的应用。然后你可以读我的第二本书来学习[Redux](https://roadtoreact.com/course-deta
会展示给你一个代码实现  --> 「在本书中，示例应用程序的实现将会向你证明，不需要Redux也可以使用 React 构建应用程序。」

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**这本书会用到JavaScript ES6吗？** 是的。但是别担心。如果你熟悉ES5就可以了。所有的JavaScript ES6语法，在我们学习React的过程中，都逐步会从ES5转换成ES6.每个语法都会有详细的解释。这本书不只是用来学习React，同时也包含所有相关的ES6语法。
ES6 后面是。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**如果我在书中发现一些问题，有地方可以帮助解决吗？** 如果你发现问题，请加入Slack聊天组。另外，你可以看看本书[Github上的问题](https://github.com/rwieruch/the-road-to-learn-react/issues)。有可能你的问题已经有人遇到了，并且解决方案也在上面。如果找不到同样的问题，请新建一个新的问题来解释你遇到的麻烦，比如提供一个截图，和一
比如页数、Node 版本

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**我能提供帮助来改进这本书吗？** 是的。你可以在[在GitHub上贡献](https://github.com/rwieruch/the-road-to-learn-react)直接提出你的想法和代码。我并不声称自己是一个专家，或者是一个英语母语作者。会非常感谢您的帮助。
自谦的话应该就是「不宣称」

我并不宣称自己是一个专家，也不是用英语母语进行写作。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**我能提供帮助来改进这本书吗？** 是的。你可以在[在GitHub上贡献](https://github.com/rwieruch/the-road-to-learn-react)直接提出你的想法和代码。我并不声称自己是一个专家，或者是一个英语母语作者。会非常感谢您的帮助。
缺了「我」会非常感谢

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +**写这本书的有什么特别的出发点吗？** 是的。我想让你花点时间想想，怎么样一个人适合学习React。这个人已经有了一些兴趣，可能已经学习了一段时间，或者可能并没有发现自己其实可以学习React。你可以推荐这本书给他。这对我来说非常有意义。这本书的意义就在于可以被推荐给别人。
「我希望你能花点时间想一想谁比较适合学习 React。这个人可能已经表现出一些兴趣，可能已经学习过一段时间，或者有可能并没有发现自己其实可以学习 React。」

「你可以找到他们然后把这本书分享给他。这对我真的非常重要，这本书就旨在与他人分享。」

这段话跟 finalwords 里面很像

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +我希望这本书在你打算写一个应用的时候，能够教会你React。这是一个实践性很强的React学习指南，而不是一个React资料索引。你会在这本书的指引下写一个Hacker News(译者注：一个著名黑客论坛)应用，会需要和真实API交互。她包括了很多有趣的话题，包括React状态管理，缓存和交互效果（排序和搜索）。在这个过程中你可以学到React的最佳实践和设计模式。
Hacker News(译者注：一个著名黑客论坛)



要用中文括号啊，（） 😂

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +一般来说，本书每一章都会在前一章基础上继续搭建。每一章都会教你一些新的知识点。务必不要跳过任何内容。你应该认同每一个步骤。你可以自己写出实现，然后阅读书中的内容。每一章之后，我提供了一些阅读资料和练习题。如果你真的想学好React，我非常推荐读完这些阅读资料并上手完成练习题。完成一章的学习之后，请保证自己对所学内容熟练掌握之后，再继续后面的章节。
internalize 应该就是实践吸收的意思，认同有点儿奇怪，强加于人的感觉。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +最终，你会有一个完整的可以部署上线的应用。我非常渴望能看到你的杰作，如果你完成了这本书，请给我发消息。最后一章会给你很多选择来继续React的学习和应用。一般来说你会在[我的个人网站](https://www.robinwieruch.de/)找到非常多的React的相关话题。
总之你会发现在 [我的个人网站](https://www.robinwieruch.de/) 有非常多的 React 的相关话题。

2017-12-06 15:13 UTC, JimmyLv commented on manuscript/foreword-cn.md
> +既然你在看这本书，我猜你还是个React新手。真是太好了。最后我希望你能给我你的反馈，来帮助我完善学习资料，从而让所有人都掌握React。你可以直接提交代码到[GitHub](https://github.com/rwieruch/the-road-to-learn-react)，或者在[Twitter](https://twitter.com/rwieruch)给我发消息。
来帮助我完善学习资料，以帮助人人都可以掌握 React。（「让所有人都掌握 React」这简直太无理了啊，😂）

2017-12-14 09:41 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +您会学着构建您自己的React应用。这个应用会涉及一些真正可用的功能，比如分页，客户端缓存，以及像搜索和排序这样的交互功能。另外在这个过程中，您会慢慢从JavaScript ES5过渡到JavaScript ES6.我希望这本书能承载着我对React和JavaScript的热情，并让您能够开始您的开发旅程。
这里有点意译，captures my enthusiasm  - 充分体现我的热情 - 承载着我的热情，还是有点犹豫

2017-12-14 10:03 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +**[Muhammad Kashif](https://twitter.com/appsdevpk/status/848625244956901376):** “《》是一本独一无二的书，我推荐给所有的学生或者对React有专业兴趣的初级或高级的读者。她是一个包括了很难在其他地方找到的有启发性的小提示和技术点的合集，最棒的是书中的例子和引用都很缜密的放到一起解决了同一个问题，我有17年的互联网和桌
use of examples and references to the same problem, 我的理解和翻译一致，书中虽然引用了大量例子和引用，最后都被用到我们要解决的问题上，体现了编写本书令人惊叹地缜密。

2017-12-14 10:08 UTC, LeiZeng commented on manuscript/foreword-cn.md
> +**[Austin Green](https://twitter.com/AustinGreen/status/845321540627521536):** “非常感谢，真的很喜欢这本书。完美的学习曲线，不管是React，ES6，还是抽象编程概念。”
这个我想了很久，我还是觉得抽象更好。比如我们说，higher level speaking,  是要避免细节，那么就是抽象一些来讲的意思。

2017-12-18 14:29 UTC, JimmyLv approved these changes

2017-12-18 14:32 UTC, JimmyLv approved these changes

2017-12-18 14:38 UTC, merged