[ liujiefengfeng ] - chapter5 - Translate to chinese. Version 1.0
the-road-to-learn-react/the-road-to-learn-react-chinese pull request #21
Opened 2017-12-07 10:28 UTC by liujiefengfeng

译文翻译完成，resolve #5 
有10个地方，不是很确定，添加注释 (NOTE:原文)。

2017-12-25 13:41 UTC, JimmyLv commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
哈哈，先把这个给 delete 掉吧~

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +有时我们需要在 React 中与 DOM 节点进行交互。`ref`属性可以让我们访问元素中的一个节点。通常，访问 DOM 节点是 React 中的一种反模式，因为我们应该遵循它的声明式编程和单向数据流。当我们实现第一个搜索输入组件时，就已经了解这些了。(NOTE:You have learned about it when you have introduced your first searc
introduced 翻译成‘初次接触’吧，即「当你初次接触第一个搜索输入框的时候，就已经了解过它了。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +有时我们需要在 React 中与 DOM 节点进行交互。`ref`属性可以让我们访问元素中的一个节点。通常，访问 DOM 节点是 React 中的一种反模式，因为我们应该遵循它的声明式编程和单向数据流。当我们实现第一个搜索输入组件时，就已经了解这些了。(NOTE:You have learned about it when you have introduced your first searc
措辞你可以再想想啦

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +> to use the DOM API (focus, media playback etc.)
playback 要翻译成「回放」不？有点儿奇怪就是了。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +让我们通过 Search 组件这个例子看一下。当应用程序第一次渲染时，input 字段应该被聚焦。这是需要访问 DOM API 的一种用例。本章将展示它是如何工作的，但由于它对于应用程度并不是很有用，所以我们将在本章之后省略这些更改。尽管如此，你仍然可以为自己的应用程序保留它。
建议把代词“它”适当地翻译成具体的事物。这句话里面‘它’太多了，不然看到最后这句「尽管如此，你仍然可以为自己的应用程序保留它。」很莫名其妙。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +通常，无状态组件和ES6类组件中都可以使用`ref`属性。在聚焦 input 字段的用例中，我们需要一个生命周期方法。这就是为什么接下来会先展示如何在 ES6 类组件中使用`ref`属性。
在聚焦 input 字段的用例中，我们「就」需要一个生命周期方法

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +通常，无状态组件和ES6类组件中都可以使用`ref`属性。在聚焦 input 字段的用例中，我们需要一个生命周期方法。这就是为什么接下来会先展示如何在 ES6 类组件中使用`ref`属性。
这里的 by using 应该是「通过……来展示……」而不是「使用……」？结合上下文看一看呢？

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +ES6 类组件的`this`对象可以帮助我们用`ref`属性引用 DOM 节点。
通过 `ref` 属性来引用 DOM 节点。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在，当组件挂载的时候，我们可以通过使用`this`对象，相应的生命周期方法和 DOM API ，聚焦在input 字段上。
翻译腔有点儿重，可以调整一下语序。

「现在，当组件挂载的时候，我们可以通过使用 `this` 对象，相应的生命周期方法和 DOM API ，聚焦在 input 字段上。」
    
「现在，你可以通过使用 `this` 对象、适当的生命周期方法和 DOM API 在组件挂载的时候来聚焦 input 字段。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +当应用程序渲染时，input 字段应该被聚焦。这是`ref`属性的基本用法。(NOTE: That's it basically for using the ref attribute.)
当应用程序渲染时，input 字段应该被聚焦。这就是 `ref` 属性的基本用法。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在我们能够访问 input DOM 元素。但是这对于聚焦 input 字段这个用例而言，没什么用。因为在无状态组件中，没有生命周期方法去触发聚焦事件。但是在将来，你可能会遇到其他一些合适的需要在无状态组件中使用`ref`属性的情况。
这里并没有「但是」的转折啦。上面的代码例子是说如何访问到 input node `ref={(node) => input = node}`，所以后面只是解释在之前那个例子里面没办法通过生命周期方法去触发事件。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +## 加载 ...
用中文省略号吧。 加载……

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +请求是异步的，此时应该向用户显示一些即将发生事情的反馈。(NOTE: The request is asynchronous and you should show your user some feedback that something is about to happen.) 让我们在 `src／App.js` 中定义一个可重用的 Loading 组件。
我发现你的翻译是从 Google Translation 直接 copy 过来的，哈哈哈。（因为我也会这样借助工具辅助，除了谷歌还会用有道。）


「请求是异步的，此时应该向用户展示某些事情即将发生的反馈。」

一个 tip 就是只要把语句从被动化为主动，瞬间就清晰啦。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +最后一步，我们将在应用程序中使用 Loading 组件。基于加载状态 (isLoading) 的条件渲染将决定是显示 Loading 组件还是 Button 组件。Button 组件是一个获取更多数据的按钮。
基于加载状态 (isLoading) 的条件来决定渲染 Loading 组件或 Button 组件。后者为一个用于获取更多数据的按钮。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +由于我们在`componentDidMount（）`中发起请求，当启动应用程序的时候，Loading 组件会显示。此时，因为列表是空的，所以不显示 Table 组件。当响应数据从 Hacker News API 返回时，返回的数据会通过 Table 组件显示出来，加载状态 (isLoading) 设置为 false，然后 Loading 组件消失。同时，出现了可以获取更多的数据的“More”按钮
「 由于我们在 `componentDidMount（）` 中发起请求，当启动应用程序的时候，Loading 组件会显示。」

=> 「Loading 组件会在应用程序启动的时候显示。」

整个 Review 下来，感觉就是你的短句特别多。但其实更建议合并成一句话，但是更精简。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +HOC可用于不同的情况，比如：准备属性 (NOTE: prepare properties)，管理状态或更改组件的表示形式。其中一种情况是将 HOC 用于帮助实现条件渲染。想象一下，现在有一个 List 组件，它可以渲染一个列表或者什么也不渲染，因为列表可以为空。当没有列表的时候，HOC 可以屏蔽掉这个不显示任何内容的列表。另一方面，这个简单的 List 组件不关心列表存不存在，它只关心渲染列表
为……准备 => 「为……装备」，其实也可以意译啦，我的理解就是通过 HOC 给组件装配/增添一些 Props。
用顿号**`、`** => 准备属性、管理状态或更改组件的表示形式

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +HOC可用于不同的情况，比如：准备属性 (NOTE: prepare properties)，管理状态或更改组件的表示形式。其中一种情况是将 HOC 用于帮助实现条件渲染。想象一下，现在有一个 List 组件，它可以渲染一个列表或者什么也不渲染，因为列表可以为空。当没有列表的时候，HOC 可以屏蔽掉这个不显示任何内容的列表。另一方面，这个简单的 List 组件不关心列表存不存在，它只关心渲染列表
「什么也不渲染」翻得很好。

还可以调换一下语序。 =>

「想象一下现在有一个 List 组件，由于列表可以为空或无，那么它可以渲染一个列表或者什么也不渲染。」

anymore 没翻出来。=> 「另一方面，这个简单的 List 组件不再需要关心列表存不存在，它只关心渲染列表。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +在这个例子中，输入组件将和输出组件一样。什么都没发生。它渲染与输入组件相同的实例，并将所有的属性(props)传递给输出组件。但是这个 HOC 没意义。我们来增强输出组件。当加载状态 (isLoading) 为 true 时，组件显示 Loading 组件，否则显示输入的组件。条件渲染是 HOC 的良好的应用场景 (NOTE: great use case )。
`。` 太多啦，英文虽然是`.`断句，但是中文里面可以合并一下。重新组织一下语言哦~

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +在这个例子中，输入组件将和输出组件一样。什么都没发生。它渲染与输入组件相同的实例，并将所有的属性(props)传递给输出组件。但是这个 HOC 没意义。我们来增强输出组件。当加载状态 (isLoading) 为 true 时，组件显示 Loading 组件，否则显示输入的组件。条件渲染是 HOC 的良好的应用场景 (NOTE: great use case )。
条件渲染是 HOC 的一种绝佳用例。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +它从对象中取出一个属性，将剩余的属性收集到 rest 中。它也适用于多个属性。你可能已经在 [解构赋值](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)中了解了它。
「它从对象中取出一个属性，并将剩余的属性保留在 rest 中，多个属性的情况也同样适用。」

既然是「已经」，那就可以接「过」。 => 「你可能已经在 [解构赋值](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) 中了解过它。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +它从对象中取出一个属性，将剩余的属性收集到 rest 中。它也适用于多个属性。你可能已经在 [解构赋值](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)中了解了它。
`rest` 应该是变量，应该是代码哦，

```md
`rest`
```

才发现是你人为加的 `rest`，其实不用呀，‘它’需要被指代出来 => 

「这段代码从 `props` 对象中取出一个属性，并保留剩下的属性。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +Loading 组件已经封装在 HOC 中，但输入组件缺失。在显示 Button 组件或 Loading 组件的用例中，Button 是 HOC 的输入组件。增强的输出组件是一个 ButtonWithLoading 的组件。
Loading 组件已经**被**封装在 HOC 中，但**缺失了**输入组件。

主谓宾要理顺呀，😂

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在所有的东西已经定义好了。最后一步，就是使用 ButtonWithLoading 组件，它接收加载状态 (isLoading) 作为附加属性。当 HOC 消费加载属性 (isLoading) 时，所有其他 props 都被传递给 Button 组件。
**被**定义好了

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在所有的东西已经定义好了。最后一步，就是使用 ButtonWithLoading 组件，它接收加载状态 (isLoading) 作为附加属性。当 HOC 消费加载属性 (isLoading) 时，所有其他 props 都被传递给 Button 组件。
「当 HOC 消费加载属性 (isLoading) 时，所有其他 props 都被传递给 Button 组件。」

这里 HOC 是主语，所以后半句继续沿用这个主语呀。

「当 HOC 消费加载属性 (isLoading) 时，再将所有其他 props 传递给 Button 组件。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +如果你认为是 App 组件有问题，现在可以选择修复该组件，或者选择接受 App 组件的新快照。因为本章介绍了 Loading 组件，我们可以在交互测试的命令行中接受已经更改的快照测试。
「接受」翻译得太生硬了。意译成「更新/认可」会不会好一些？

> 如果你认为是 App 组件有问题，现在可以选择修复该组件，或者选择接受 App 组件的新快照。

如果你认为是 App 组件出了问题，那么可以立即修复该组件，或者也可以选择更新作为新的快照。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +我们鼓励阅读[高阶组件的简单介绍](https://www.robinwieruch.de/gentle-introduction-higher-order-components/)。这篇文章介绍了另一种学习高阶组件的方法，展示了如何用函数式的方式定义高阶组件并优雅的使用它，以及使用高阶组件解决条件渲染的问题。(NOTE: shows you an elegant way to use them
「鼓励」有点儿奇怪，就是「推荐你去阅读……」吧。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +我们已经实现了客户机和服务器端搜索交互。现在我们已经拥有了 Table 组件，所以增强 Table 组件的交互性是有意义的。那接下来我们给 Table 组件引入根据列标题给每列排序的功能怎么样呢？
客户机？ 机翻被我发现了吧……

「客户端和服务器端的搜索交互功能。」

since 是因为，而且后边儿跟了所以，「因为，所以……」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +我们已经实现了客户机和服务器端搜索交互。现在我们已经拥有了 Table 组件，所以增强 Table 组件的交互性是有意义的。那接下来我们给 Table 组件引入根据列标题给每列排序的功能怎么样呢？
「那么接下来，我们**来**为 Table 组件加入根据每列的标头（似乎有这种 professional 一点的说法，可以去参考 Excel 的中文版，哈哈哈）进行排序的功能如何？」

还是有点儿奇怪，😂  你再组织一下呢？

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +你自己写一个排序函数，但是一般这种情况，我个人更喜欢使用第三方工具库。[lodash](https://lodash.com/)是其中的一个工具库，你可以使用任何适合的库。我们接下来安装 lodash 并使用它的排序方法。
[lodash](https://lodash.com/) 就是这些工具库之一，当然你也可以选择适用于你的任何第三方库。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +你自己写一个排序函数，但是一般这种情况，我个人更喜欢使用第三方工具库。[lodash](https://lodash.com/)是其中的一个工具库，你可以使用任何适合的库。我们接下来安装 lodash 并使用它的排序方法。
让我们安装 lodash 并使用

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +Table 组件中有好几列，它们分别是标题，作者，评论和评分。你可以定义排序函数，而每个函数接受一个列表并返回按照指定属性排序过的列表。此外，还需要一个默认排序函数，该函数不做排序，只返回未排序的列表。默认排序函数是 Table 组件的初始状态。
分别是标题、作者、评论和评分

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +Table 组件中有好几列，它们分别是标题，作者，评论和评分。你可以定义排序函数，而每个函数接受一个列表并返回按照指定属性排序过的列表。此外，还需要一个默认排序函数，该函数不做排序，只返回未排序的列表。默认排序函数是 Table 组件的初始状态。
**我们**还需要一个默认的排序函数，该函数不做排序而只是用于返回未排序的列表。这将作为组件的初始状态。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +>Again your App component is responsible for storing the state of the sort. The initial state will be the initial default sort function, which doesn't sort at all and returns the input list as output
which doesn't sort at all and returns the input list as output.

这个 doesn't 是同时否定了后端的 returns 吗？

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在，我们要在App组件中定义一个新的类方法，它将`sortKey`设置为App组件的状态。之后，`sortKey` 用来选取对应的排序函数，并应用到列表上。
定义一个新的类方法，用来将 `sortKey` 设置为 App 组件的状态。  （主语依然是**我们**）

然后，这个 `sortKey` 可以被用来选取对应的排序函数并对其列表进行排序。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +Table 组件负责对列表排序。它通过`sortKey`选取`SORT`对象中对应的排序函数，并列表作为该函数的输入。之后，Table 组件将保持在排序列表上的映射。
保持……的映射？  又是机翻了吧。。。

结合代码看的意思应该是「Table 组件将在已排序的列表上继续 mapping。」

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +理论上，列表可以按照其中的任意排序函数进行排序，但是默认的排序 (sortKey) 是`NONE`，所以列表不进行排序。至此，没有人执行`onSort()`方法来改变`sortKey`。我们接下来用一行列标题来扩展表格，每个列标题会使用列中的 Sort 组件对每列进行排序。
至此，**还**没有人执行 `onSort()` 方法来改变 `sortKey`。

让我们……

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +如你所见，Sort 组件重用了我们的 Button 组件，当点击按钮时，每个传入的`sortKey`都会被`onSort（）`方法设置。现在，点击列标题，应该可以对列表进行排序了。
现在，你应该能够通过点击列标题来对列表进行排序了。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在在排序方法中，可以评判列表是否被反向排序。如果状态中的 sortKey 与传入的 sortKey 相同，并且反向状态 (isSortReverse) 尚未设置为 true，则相反--反向状态 (isSortReverse) 设置为 true。
可以判断列表是否被反向排序。

「则相反 -- 反向状态 (isSortReverse) 设置为 true。」？？？

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在 Table 组件有一个块体箭头函数去计算数据了。
现在这个 Table 组件有一个块体箭头函数用于计算数据。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +最后值得一提，为了改善用户体验，我们可以思考一个开放性的问题：用户可以区分哪个列排序是被激活的吗？(NOTE: Can a user distinguish which column is actively sorted? 用户可以区分当前是根据哪一列进行排序的嘛？)目前，用户是区别不出来的。我们可以给用户一个视觉反馈。
我们可以思考这样一个开放式问题：

「**用户可以区分当前是根据哪一列进行排序的吗？**」 没毛病。


目前为止，用户是区别不出来的。

2017-12-25 13:41 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在在 Sort 组件中，基于`sortKey`和`activeSortKey`，我们知道排序是否被激活。给 Sort 组件增加一个`className`属性，如果排序被激活，给用户一个视觉上响应。
现在在 Sort 组件中，我们可以基于 `sortKey` 和 `activeSortKey`**得知**排序是否被激活。给 Sort 组件增加一个 `className` 属性，如果排序被激活，给用户一个视觉上响应。

2017-12-25 13:53 UTC, JimmyLv reviewed
整体来看短句太多啦，可以尝试在通读的时候合并一些很短的句子：比如化被动为主动，把形容词（或修饰语句）提前，合理运用中文连词「X过、用于、使得、来 etc」，否则读者在看的时候不然显得思维太散乱了。

2017-12-25 13:53 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在，我们可以使用它的条件类来定义组件的`className`。
条件类？ conditional 是条件式语句的意思。



现在，我们可以通过条件式语句来定义组件的 `className`。（classes 没有必要就不翻译了）

2017-12-25 13:53 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +同样，当运行测试时，会看到 Table 组件失败的快照测试，及其失败的单元测试。由于我们再次更改了组件显示，因此可以选择接受快照测试。但是必须修复单元测试。在我们的 `src / App.test.js`文件中，需要为 Table 组件提供`sortKey`和`isSortReverse`。
当运行测试时，我们会看到 Table 组件失败的快照测试跟单元测试。

2017-12-25 13:53 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +  * 一个简洁的库帮助实现条件 classNames
列表都变成名词断句会好一些~

 * 通过 ref 属性引用 DOM 节点
 * 高阶组件是构建高级组件的常用方法
 * 高级交互在 React 中的实现
 * 帮助实现条件 classNames 的一个优雅库

2017-12-25 13:53 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> + 你可以在[官方 repo ](https://github.com/rwieruch/hackernews-client/tree/4.5)找到源代码。
官方代码库

2017-12-25 14:10 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +> to use the DOM API (focus, media playback etc.)
这个是参照 html5, video 有个 playbackspeed 属性，W3C  上面给出的是 `播放速度`

2017-12-25 14:13 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +让我们通过 Search 组件这个例子看一下。当应用程序第一次渲染时，input 字段应该被聚焦。这是需要访问 DOM API 的一种用例。本章将展示它是如何工作的，但由于它对于应用程度并不是很有用，所以我们将在本章之后省略这些更改。尽管如此，你仍然可以为自己的应用程序保留它。
后面改成：
本章将展示渲染时聚焦 input 字段是如何工作的，但由于这个功能对于应用程序并不是很有用，所以我们将在本章之后省略这些更改。尽管如此，你仍然可以为自己的应用程序保留它。

2017-12-25 14:21 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +请求是异步的，此时应该向用户显示一些即将发生事情的反馈。(NOTE: The request is asynchronous and you should show your user some feedback that something is about to happen.) 让我们在 `src／App.js` 中定义一个可重用的 Loading 组件。
不要嘲笑我……拿不准的都加 NOTE了…

2017-12-25 14:29 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +通常，无状态组件和ES6类组件中都可以使用`ref`属性。在聚焦 input 字段的用例中，我们需要一个生命周期方法。这就是为什么接下来会先展示如何在 ES6 类组件中使用`ref`属性。
前文有一句 `use the ref attribute in both functional stateless components and ES6 class components`，翻译成  `无状态组件和ES6类组件中都可以使用 ‘ref’ 属性`. 我觉得 「使用……」 回上下文连贯一点……从语法上来说，「通过……来展示……」 好像更好一点…… 让我思考一下

2017-12-25 14:33 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +现在我们能够访问 input DOM 元素。但是这对于聚焦 input 字段这个用例而言，没什么用。因为在无状态组件中，没有生命周期方法去触发聚焦事件。但是在将来，你可能会遇到其他一些合适的需要在无状态组件中使用`ref`属性的情况。
啊……这段话里面，有两个「但是」。

2017-12-25 14:38 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +由于我们在`componentDidMount（）`中发起请求，当启动应用程序的时候，Loading 组件会显示。此时，因为列表是空的，所以不显示 Table 组件。当响应数据从 Hacker News API 返回时，返回的数据会通过 Table 组件显示出来，加载状态 (isLoading) 设置为 false，然后 Loading 组件消失。同时，出现了可以获取更多的数据的“More”按钮
这个 
「由于我们在 componentDidMount（） 中发起请求」 这段话，不要了嘛？

2017-12-25 14:44 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +在这个例子中，输入组件将和输出组件一样。什么都没发生。它渲染与输入组件相同的实例，并将所有的属性(props)传递给输出组件。但是这个 HOC 没意义。我们来增强输出组件。当加载状态 (isLoading) 为 true 时，组件显示 Loading 组件，否则显示输入的组件。条件渲染是 HOC 的良好的应用场景 (NOTE: great use case )。
我跟我的pair 在 `良好的应用场景` / `惯用场景`  里面挑了一个…… 都没有想到 `绝佳用例`

2017-12-25 14:56 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +它从对象中取出一个属性，将剩余的属性收集到 rest 中。它也适用于多个属性。你可能已经在 [解构赋值](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)中了解了它。
「 它 」 =>「这段代码」 明确指代，这个很好。

但是这个 rest 在给出的MDN的链接里面，详细讲了结构赋值。里面有一段
`Rest in Object Destructuring（对象解构中的Rest）` 
翻译成这样
`Rest/Spread Properties for ECMAScript 提案（阶段3）将rest语法添加到解构中。Rest 属性收集尚未被解构模式拾取的剩余可枚举属性键。`
这个是保持跟 MDN 一样呢，还是我们意译呢～

2017-12-25 15:05 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +Table 组件中有好几列，它们分别是标题，作者，评论和评分。你可以定义排序函数，而每个函数接受一个列表并返回按照指定属性排序过的列表。此外，还需要一个默认排序函数，该函数不做排序，只返回未排序的列表。默认排序函数是 Table 组件的初始状态。
这个语序，很赞

2017-12-25 15:09 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +>Again your App component is responsible for storing the state of the sort. The initial state will be the initial default sort function, which doesn't sort at all and returns the input list as output
没有吧……没有否定returns
因为代码写成这样 `NONE: list => list`
那么这个就是没有对list进行排序，将输入的list作为输出的list。

2017-12-25 15:14 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +Table 组件负责对列表排序。它通过`sortKey`选取`SORT`对象中对应的排序函数，并列表作为该函数的输入。之后，Table 组件将保持在排序列表上的映射。
嗯，是呢。可是这个机翻，比我翻译得要好。尴尬😅

2017-12-25 15:23 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +现在在排序方法中，可以评判列表是否被反向排序。如果状态中的 sortKey 与传入的 sortKey 相同，并且反向状态 (isSortReverse) 尚未设置为 true，则相反--反向状态 (isSortReverse) 设置为 true。
我觉得这段话就是在解释这段代码👇
` const isSortReverse = this.state.sortKey === sortKey && !this.state.isSortReverse;`

直译过来就是
` sortKey 与传入的 sortKey 相同，并且反向状态 (isSortReverse) 尚未设置为 true，那么反向状态（isSortReverse）就为true。`
或者
` sortKey 与传入的 sortKey 相同，并且反向状态 (isSortReverse) 尚未设置为 true，那么此时就是反向排序，反向状态（isSortReverse）就为true。`


如果翻译成这样，上下文不太连贯的样子 👇
` sortKey 与传入的 sortKey 相同，并且反向状态 (isSortReverse) 尚未设置为 true，可以判断列表是否被反向排序。`

或者翻译成这样👇
`根据 sortKey 与传入的 sortKey 是否相同，以及反向状态 (isSortReverse) 的值，可以判断列表是否被反向排序。`

2017-12-25 15:24 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +由于我们在`componentDidMount（）`中发起请求，当启动应用程序的时候，Loading 组件会显示。此时，因为列表是空的，所以不显示 Table 组件。当响应数据从 Hacker News API 返回时，返回的数据会通过 Table 组件显示出来，加载状态 (isLoading) 设置为 false，然后 Loading 组件消失。同时，出现了可以获取更多的数据的“More”按钮
还是要的啦，我只是没复制上.

2017-12-25 15:26 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +它从对象中取出一个属性，将剩余的属性收集到 rest 中。它也适用于多个属性。你可能已经在 [解构赋值](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)中了解了它。
强行插入那么长一段话也有点儿奇怪，还是简单表达意思就好啦

2017-12-25 15:27 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +最后值得一提，为了改善用户体验，我们可以思考一个开放性的问题：用户可以区分哪个列排序是被激活的吗？(NOTE: Can a user distinguish which column is actively sorted? 用户可以区分当前是根据哪一列进行排序的嘛？)目前，用户是区别不出来的。我们可以给用户一个视觉反馈。
这里翻译成
`用户可以区分哪个列排序是被激活的吗？`
主要是想跟下文的排序激活做呼应……不然后来就直接写 `排序是否被激活`，会比较突然……

2017-12-25 15:32 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +>Again your App component is responsible for storing the state of the sort. The initial state will be the initial default sort function, which doesn't sort at all and returns the input list as output
那么 and 就翻译成「**而只是**将输入的list作为输出」

2017-12-25 15:32 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +理论上，列表可以按照其中的任意排序函数进行排序，但是默认的排序 (sortKey) 是`NONE`，所以列表不进行排序。至此，没有人执行`onSort()`方法来改变`sortKey`。我们接下来用一行列标题来扩展表格，每个列标题会使用列中的 Sort 组件对每列进行排序。
至此，还没有人执行`onSort()`方法来改变`sortKey`。让我们接下来用一行列标题来扩展表格，每个列标题会使用列中的 Sort 组件对每列进行排序。

2017-12-25 15:33 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +同样，当运行测试时，会看到 Table 组件失败的快照测试，及其失败的单元测试。由于我们再次更改了组件显示，因此可以选择接受快照测试。但是必须修复单元测试。在我们的 `src / App.test.js`文件中，需要为 Table 组件提供`sortKey`和`isSortReverse`。
我没有做这个例子，我不确定，快照测试和单元测试，是不是都是for the Table component

2017-12-25 15:34 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +现在在排序方法中，可以评判列表是否被反向排序。如果状态中的 sortKey 与传入的 sortKey 相同，并且反向状态 (isSortReverse) 尚未设置为 true，则相反--反向状态 (isSortReverse) 设置为 true。
啊哈，我明白你的 -- 的意思啦，用中文的破折号 `——` 才表意啊，不然之前我就觉得莫名奇妙，😂

2017-12-25 15:34 UTC, liujiefengfeng commented on manuscript/chapter5-cn.md
> +  * 一个简洁的库帮助实现条件 classNames
这个很赞

2017-12-26 09:04 UTC, JimmyLv commented on manuscript/chapter5-cn.md
> +最后值得一提，为了改善用户体验，我们可以思考一个开放性的问题：用户可以区分哪个列排序是被激活的吗？(NOTE: Can a user distinguish which column is actively sorted? 用户可以区分当前是根据哪一列进行排序的嘛？)目前，用户是区别不出来的。我们可以给用户一个视觉反馈。
嗯嗯，是的。

2017-12-26 09:04 UTC, JimmyLv requested changes
改好了之后记得把英文 remove 掉哦~

2017-12-26 15:43 UTC, JimmyLv approved these changes

2017-12-26 15:43 UTC, merged