Chap 6
the-road-to-learn-react/the-road-to-learn-react-chinese pull request #22
Opened 2017-12-07 10:46 UTC by futantan

译文翻译完成，resolve #6

2017-12-11 13:44 UTC, lazurey requested changes
基本都是遣词上的更改，麻烦过一下，多谢。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在前面的章节中，你已经学会了 React 基本的状态管理，本章将会更加深入地进行学习。你将学习到状态管理的最佳实践，如何去应用它们以及为什么可以考虑使用第三方的状态管理库。
你已经学会了 React 基本的状态管理，本章将会更加深入地进行学习。
-> 你已经学习了 React 中状态管理的基础知识，本章将会深入这个话题。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在你的应用程序中，只有 App 是具有状态的 ES6 组件。在该组件的方法中，包含了许多应用程序的状态和业务的处理逻辑。可能你已经注意到了，Table 组件被传入了大量的属性参数。而这些参数中的绝大部分只有在 Table 组件中才被用到。所以有人可能会提出 App 组件拥有这些只有在 Table 组件中才会用的参数是毫无意义的。
在你的应用程序中
* 前面几章application都只翻译成了”应用“
-> 在你的应用中

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在你的应用程序中，只有 App 是具有状态的 ES6 组件。在该组件的方法中，包含了许多应用程序的状态和业务的处理逻辑。可能你已经注意到了，Table 组件被传入了大量的属性参数。而这些参数中的绝大部分只有在 Table 组件中才被用到。所以有人可能会提出 App 组件拥有这些只有在 Table 组件中才会用的参数是毫无意义的。
Table 组件被传入了大量的属性参数。
-> 我们给 Table 组件传入了大量属性。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在你的应用程序中，只有 App 是具有状态的 ES6 组件。在该组件的方法中，包含了许多应用程序的状态和业务的处理逻辑。可能你已经注意到了，Table 组件被传入了大量的属性参数。而这些参数中的绝大部分只有在 Table 组件中才被用到。所以有人可能会提出 App 组件拥有这些只有在 Table 组件中才会用的参数是毫无意义的。
所以有人可能会提出 App 组件拥有这些只有在 Table 组件中才会用的参数是毫无意义的。
-> 所以有人可能会得出”App 组件不需要知道这些参数“的结论。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +整个排序功能只有在 Table 组件中才被用到，你可以将其移动到 Table 组件中，因为 App 组件根本不需要了解这些信息。将子状态（substate）从一个组件移动到其他组件中的重构过程被称为*状态提取*。在这里，你想要将 App 组件中用不到的状态移动到 Table 组件中，这里状态从父组件向下移动到子组件中。
整个排序功能只有在 Table 组件中才被用到
-> 整个排序功能只有在 Table 组件中用到了

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +整个排序功能只有在 Table 组件中才被用到，你可以将其移动到 Table 组件中，因为 App 组件根本不需要了解这些信息。将子状态（substate）从一个组件移动到其他组件中的重构过程被称为*状态提取*。在这里，你想要将 App 组件中用不到的状态移动到 Table 组件中，这里状态从父组件向下移动到子组件中。
在这里，你想要将 App 组件中用不到的状态移动到 Table 组件中，这里状态从父组件向下移动到子组件中。
* 还是用句号断句
->
在这里，你想要将 App 组件中用不到的状态移动到 Table 组件中。这里的状态是从父组件到子组件向下移动。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +为了能够在 Table 组件中管理状态和添加方法，需要将其改写成 ES6 类的形式。从无状态的函数组件（functional stateless component）到 ES6 类形式组件的重构非常简单明了。
为了能够在 Table 组件中管理状态和添加方法
-> 为了能够在 Table 组件中管理状态、使用类方法

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +为了能够在 Table 组件中管理状态和添加方法，需要将其改写成 ES6 类的形式。从无状态的函数组件（functional stateless component）到 ES6 类形式组件的重构非常简单明了。
functional stateless component
无状态的函数组件
* 这个在第二章翻译成”函数式无状态组件“，需要统一一下 refer to #19

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +无状态函数组件形式的 Table 组件：
无状态函数组件形式的 Table 组件：

* 统一”函数式无状态组件“的用词

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +别忘了将移动后的状态和  `onSort()` 方法从 App 组件中移除。
别忘了将移动后的状态和  `onSort()` 方法从 App 组件中移除。

-> 别忘了将挪走的状态和  `onSort()` 方法从 App 组件中移除。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +除此之外，你还可以让 Table 组件更加轻量。可以将从 App 组件中传入的参数移除，因为现在这些参数可以在 Table 组件内部由状态进行处理。
可以将从 App 组件中传入的参数移除
->
你还可以去掉从 App 组件传入的属性

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +除此之外，你还可以让 Table 组件更加轻量。可以将从 App 组件中传入的参数移除，因为现在这些参数可以在 Table 组件内部由状态进行处理。
因为现在这些参数可以在 Table 组件内部由状态进行处理。
-> 因为现在这些属性可以由 Table 组件的内部状态控制。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +现在你就可以使用 Table 组件内的 `onSort()` 方法和其内部的 state 了。
现在你就可以使用 Table 组件内的 `onSort()` 方法和其内部的 state 了。

* 之前讨论过，state没加`state`尽量翻译成中文。

->
现在你就可以使用 Table 组件内的 `onSort()` 方法和状态了。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +状态提取的过程也可以反过来：从子组件到父组件，这种情形被称为状态提升。想象一下，你在子组件中处理了内部的状态信息。现在为了满足新的需求，在其父组件中也显示该组件的状态信息，你需要将状态提升到父组件中。但是情况还不止这些，想象一下如果你想在子组件的兄弟组件上显示状态相关信息，你还是需要将状态提升到父组件中。在父组件中处理内部状态信息，同时将状态信息暴露给相关的子组件。
但是情况还不止这些，想象一下如果你想在子组件的兄弟组件上显示状态相关信息

* 尽管作者用了两个Imagine，但在中文里四个字重复的感觉更加明显，所以最好换一个词
* 这里的状态应该是特指该组件状态

-> 但情况还不止这些，假如你需要在子组件的兄弟组件上显示该组件的状态，

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +* 了解更多关于 [React 的状态提升](https://facebook.github.io/react/docs/lifting-state-up.html)
了解更多关于xxx 的内容

* 了解更多后面统一加上”的内容“，风格统一

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +至此，你已经使用过 React 的  `setState()` 方法来管理组件的内部状态信息。你可以给该函数传入一个对象来改变部分的内部状态信息。
内部状态信息

* 可以把”信息“都去掉，下同。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +为什么你会需要第二种形式呢？使用函数作为参数而不是对象，有一个非常重要的应用场景，就是当更新状态的时候需要取决于之前的状态或者属性。如果不使用函数参数的形式，组件的内部状态管理可能会引起 bug。
就是当更新状态的时候需要取决于之前的状态或者属性
-> 就是当更新状态需要取决于之前的状态或者属性的时候

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +当更新状态需要取决于之前的状态或者属性时，为什么使用对象而不是函数会引起 bug 呢？React 的 `setState()` 方法是异步的。React 批次执行 `setState()` 方法，最终会全部执行完毕。如果你的 `setState()` 方法依赖于之前的状态或者属性的话，有可能在批次执行期间，状态或者属性的值已经被改变了。
React 的 `setState()` 方法是异步的。
-> 这是因为 React 的 `setState()` 方法是异步的。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +想象一下像 `fooCount` 和 `barCount` 这样的状态或属性值，在你调用  `setState()` 方法的时候在其他地方被异步地改变了。在不断膨胀的应用程序中，你会有多个  `setState()` 调用。因为 `setState()` 是异步执行的，你可能像上面的例子一样，依赖的值已经被改变了。
属性值
-> 属性

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +想象一下像 `fooCount` 和 `barCount` 这样的状态或属性值，在你调用  `setState()` 方法的时候在其他地方被异步地改变了。在不断膨胀的应用程序中，你会有多个  `setState()` 调用。因为 `setState()` 是异步执行的，你可能像上面的例子一样，依赖的值已经被改变了。
依赖的值已经被改变了。
-> 依赖了一个已经过期的值。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +使用函数参数形式的话，传入 `setState()` 方法的参数是一个回调，该回调会在被执行时传入状态和属性值。尽管 `setState()` 方法是异步的，但是回调会传入调用时的状态和属性值。
但是回调会传入调用时的状态和属性值。
->
但是通过回调函数，它使用的是执行那一刻的状态和属性。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +你从 state 变量中提取了一些值，但是异步的状态更新依赖于之前的状态信息。现在你可以使用函数参数的形式来防止因为脏状态信息造成的 bug。
但是异步的状态更新依赖于之前的状态信息
-> 但是更新状态时异步地依赖于之前的状态。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +你从 state 变量中提取了一些值，但是异步的状态更新依赖于之前的状态信息。现在你可以使用函数参数的形式来防止因为脏状态信息造成的 bug。
现在你可以使用函数参数的形式来防止因为脏状态信息造成的 bug。

* 去掉”因为“

->
现在你可以使用函数参数的形式来防止脏状态信息造成的 bug。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +你可以将已经实现的逻辑移动到函数内部。只需将在 `this.state` 上的操作改为 `prevState` 。
你可以将已经实现的逻辑移动到函数内部。只需将在 `this.state` 上的操作改为 `prevState` 。

* 改成用逗号断句更连贯一些。

->
你可以将已经实现的逻辑全部移动到函数内部，只需将在 `this.state` 上的操作改到 `prevState` 上。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +如此可以修复脏状态导致的问题。还有一个可以改进的地方。因为它是一个函数，你可以将该函数提取出来从而改善代码的可读性。这是使用函数参数形式相比于对象形式的另一个好处，该函数可以独立于组件。但是你需要使用一个高阶函数并将 result 传给它。毕竟，你想根据 API 的获取结果来更新状态。
但是你需要使用一个高阶函数并将 result 传给它。

* result 需要翻译

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +`updateSearchTopStoriesState()` 是一个高阶函数，它需要返回一个函数。你可以在 App 组件之外定义这个高阶函数。请注意现在函数的签名有了一些变化。
它需要返回一个函数。

* 因为这两句颠倒了，所以因果关系也要颠倒。

-> 因为它返回一个函数

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +搞定！`setState()` 中函数参数形式相比于对象参数来说，能够阻止潜在的 bug 同时能够提高代码的可读性和可维护性。此外，它可以在 App 组件之外进行测试。你可以将其导出并写个测试来当作练习。
能够阻止潜在的 bug 同时能够提高代码的可读性和可维护性。
-> 
在预防潜在 bug 的同时，还可以提高代码的可读性和可维护性。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +* 了解更多关于[在 React 中正确使用 state](https://facebook.github.io/react/docs/state-and-lifecycle.html#using-state-correctly)
了解更多关于 xxx  的内容

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +* 重新跑一遍测试，确保一些正常工作
一些 -> 一切

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +前面的章节已经说明，状态管理在大型的应用程序中是个非常关键主题。通常来说，不仅是 React 还有很多其他的单页面应用框架面临这样的问题。近些年来应用程序变得越来越复杂。现在 web 应用程序面临的一个重大挑战是如何驾驭和控制状态。
是个非常关键主题 -> 是一个至关重要的话题

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +前面的章节已经说明，状态管理在大型的应用程序中是个非常关键主题。通常来说，不仅是 React 还有很多其他的单页面应用框架面临这样的问题。近些年来应用程序变得越来越复杂。现在 web 应用程序面临的一个重大挑战是如何驾驭和控制状态。
通常来说，不仅是 React 还有很多其他的单页面应用框架面临这样的问题。
->
总体来说，不光是 React ，很多单页面应用（SPA）框架都面临这个问题。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +前面的章节已经说明，状态管理在大型的应用程序中是个非常关键主题。通常来说，不仅是 React 还有很多其他的单页面应用框架面临这样的问题。近些年来应用程序变得越来越复杂。现在 web 应用程序面临的一个重大挑战是如何驾驭和控制状态。
现在 web 应用程序面临的一个重大挑战是如何驾驭和控制状态。
->
当今的 web 应用面临的一个重大挑战就是如何驾驭和控制状态。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在不断膨胀的应用程序中，推断状态的变化变得更加困难。`setState()` 方法使用对象形式而不是函数形式的话，如果在脏状态上进行操作，则可能会引入 bug。为了能够共享状态或者在兄弟组件之间隐藏不必要的状态，你需要将状态进行提升或者降低。有可能组件需要将其状态进行提升，因为它的兄弟组件依赖于这些状态。有可能用到其状态的兄弟组件在组件树中相隔甚远，所以你可能需要在其整个组件树中共享该状态。这样
推断状态的变化变得更加困难。
-> 推断状态的变化随之变得困难。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在不断膨胀的应用程序中，推断状态的变化变得更加困难。`setState()` 方法使用对象形式而不是函数形式的话，如果在脏状态上进行操作，则可能会引入 bug。为了能够共享状态或者在兄弟组件之间隐藏不必要的状态，你需要将状态进行提升或者降低。有可能组件需要将其状态进行提升，因为它的兄弟组件依赖于这些状态。有可能用到其状态的兄弟组件在组件树中相隔甚远，所以你可能需要在其整个组件树中共享该状态。这样
有可能组件需要将其状态进行提升，
-> 有些状况下，组件需要将其状态提升

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +在不断膨胀的应用程序中，推断状态的变化变得更加困难。`setState()` 方法使用对象形式而不是函数形式的话，如果在脏状态上进行操作，则可能会引入 bug。为了能够共享状态或者在兄弟组件之间隐藏不必要的状态，你需要将状态进行提升或者降低。有可能组件需要将其状态进行提升，因为它的兄弟组件依赖于这些状态。有可能用到其状态的兄弟组件在组件树中相隔甚远，所以你可能需要在其整个组件树中共享该状态。这样
有可能用到其状态的兄弟组件在组件树中相隔甚远

* 这里不是兄弟组件

-> 也有可能你需要和相隔甚远的组件共享状态

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +因为以上的这些原因，存在着一些独立的解决方案来解决状态管理问题。这些方案不仅仅可以在 React 中使用，但是却使得 React 的生态更加繁荣。你可以使用不同的解决方案来解决你的问题。为了解决状态管理越来越复杂的问题，你可能听说过 [Redux](http://redux.js.org/docs/introduction/) 或者 [MobX](https://mobx.js.org/)。你可
为了解决状态管理越来越复杂的问题，你可能听说过

-> 为了解决规模化的状态管理问题，你可能已经听说过

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +因为以上的这些原因，存在着一些独立的解决方案来解决状态管理问题。这些方案不仅仅可以在 React 中使用，但是却使得 React 的生态更加繁荣。你可以使用不同的解决方案来解决你的问题。为了解决状态管理越来越复杂的问题，你可能听说过 [Redux](http://redux.js.org/docs/introduction/) 或者 [MobX](https://mobx.js.org/)。你可
你可以在 React 应用中使用这些第三方库中的任何一个。
->
你可以在 React 应用中使用这两者其一。

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +* 阅读更多关于 [外部状态管理以及如何学习](https://www.robinwieruch.de/redux-mobx-confusion/)
阅读更多关于 xxx 的内容

2017-12-11 13:44 UTC, lazurey commented on manuscript/chapter6-cn.md
> +你已经学习了 React 的高级状态管理！让我们回归一下最后几章的内容。
让我们回归一下最后几章的内容。

-> 让我们回顾一下前面几章的内容。

2017-12-13 10:15 UTC, futantan commented on manuscript/chapter6-cn.md
> +为了能够在 Table 组件中管理状态和添加方法，需要将其改写成 ES6 类的形式。从无状态的函数组件（functional stateless component）到 ES6 类形式组件的重构非常简单明了。
这里的 class method 我意译成了添加方法。『添加方法』是下文中要做的改变，与类方法没有关系。文中还有好几个地方的 class method 这里直接翻译成了『方法』，并不是类方法，感觉是作者的笔误。

2017-12-13 10:17 UTC, futantan commented on manuscript/chapter6-cn.md
> +如此可以修复脏状态导致的问题。还有一个可以改进的地方。因为它是一个函数，你可以将该函数提取出来从而改善代码的可读性。这是使用函数参数形式相比于对象形式的另一个好处，该函数可以独立于组件。但是你需要使用一个高阶函数并将 result 传给它。毕竟，你想根据 API 的获取结果来更新状态。
这里 result 是传入参数的变量名称，感觉翻译之后不太好理解，越越你觉得呢？

2017-12-13 10:18 UTC, futantan commented
有两处留了 comment 可以讨论一下。其他地方都已经修改完毕，感谢 @lazurey 如此细心的校对！

2017-12-18 15:02 UTC, merged